export const UPLOAD_USERS = "UPLOAD_USERS";
export const REBOOT_USERS = "REBOOT_USERS";
export const UPLOAD_FRIENDS = "UPLOAD_FRIENDS";
export const REBOOT_FRIENDS = "REBOOT_FRIENDS";
export const ADD_TO_FRIENDS = "ADD_TO_FRIENDS";
export const DELETE_FROM_FRIENDS = "DELETE_FROM_FRIENDS";